services:
  - type: web
    name: ai-code-reviewer
    runtime: python
    buildCommand: pip install -r requirements_deploy.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GROQ_API_KEY
        value: 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
